# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a7803e32f60d403e1958f0a7b7c98345f29d90f28dc3d33960c8f888a079cb60f5ee18e0e02df0c38fe4f710a61546457248449826c310770f30c1660103db

test:
  secret_key_base: 6b7d77fb066f27a621a3560c34e7bfb53065ad6d25b492b3896fa96daadf453c45fac1da4b7e9925a4f6add25d4c1a724c1fdf36831b178fa09e888acb2ccf9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
